#!/bin/sh

# Get all staged Go files
STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".go$")

if [ -n "$STAGED_GO_FILES" ]; then
    echo "Running gofmt -s -w on staged Go files..."
    # Run gofmt on staged files
    echo "$STAGED_GO_FILES" | xargs gofmt -s -w
    # Re-add the files to the commit
    echo "$STAGED_GO_FILES" | xargs git add
fi
